apiVersion: v1
kind: Service
metadata:
  name: springlistener-mesg-svc
spec:
  ports:
  - name: port8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springlistener-mesg
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: springlistener-mesg
  name: springlistener-mesg-sts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springlistener-mesg
  template:
    metadata:
      labels:
        app: springlistener-mesg
      name: springlistener-mesg-sts
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: springbootjava.azurecr.io/springlistener:v1
        imagePullPolicy: Always
        name: springlistener-mesg
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.2
            memory: 500M
          requests:
            cpu: 0.1
            memory: 200M
